Syntax 4

SectionVerb {
	EnableSequence [
	]
	DisableSequence [
	]
}

SectionDevice."Speaker" {
	Comment "Built-in speaker (TAS2557 on PRI MI2S)"
	Value {
		PlaybackPCM "hw:SE,0"
		PlaybackChannels 2
	}
	EnableSequence [
		cdev "hw:SE"
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' on"
	]
	DisableSequence [
		cdev "hw:SE"
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' off"
	]
}